Shuffle the build around a bit
I did split it into separate projects, but then I put them back together
again because they weren't worth the effort.

Signed-off-by: Andrew Aylett <andrew@aylett.co.uk>

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -8,6 +8,7 @@ on:
 
 permissions:
   contents: read
+  checks: write
 
 jobs:
   build:
@@ -25,4 +26,18 @@ jobs:
       uses: gradle/gradle-build-action@v2
 
     - name: Execute Gradle build
-      run: ./gradlew build
+      run: ./gradlew --info build
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/build/test-results/*/TEST-*.xml'
+
+    - uses: actions/upload-artifact@v3
+      if: failure() # we don't care so much about working builds
+      with:
+        name: Built-Output
+        path: |
+          **/build/
+          !**/cache/
+          !**/caches/
